services:
  - type: web
    name: fantaaiuto-backend
    env: node
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://fantaiuto.netlify.app
      - key: DATABASE_PATH
        value: ./database/fantaaiuto.db